context:
  version: "0.3.0"
  build_number: 0

package:
  name: mujoco-usd-converter
  version: ${{ version }}

source:
  url: https://github.com/newton-physics/mujoco-usd-converter/archive/refs/tags/v${{ version }}.zip
  sha256: d9748ecfb61d3cb895b4f43dc1bf7022309235850a209ea8bc259e105eb8d485

build:
  noarch: python
  number: ${{ build_number }}
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - mujoco_usd_converter = mujoco_usd_converter.__main__:run

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - requests
    - pip
  run:
    - python >=${{ python_min }}
    - mujoco >=3.8.0.1,<3.9
    - usd-exchange >=2.2.2
    - newton-usd-schemas >=0.3.1
    - numpy-stl >=3.2
    - tinyobjloader >=2.0.0rc13

tests:
  - python:
      imports:
        - mujoco_usd_converter
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - mujoco_usd_converter --help
  # Scripts are currently failing due to missing modules:
  # * import usdex.test
  # * import omni.asset_validator
  #
  # - script:
  #     - python -m unittest discover -v -s ./tests
  #   files:
  #     source:
  #       - tests/
  #       - pyproject.toml
  #   requirements:
  #     run:
  #       - python ${{ python_min }}.*

about:
  documentation: https://github.com/newton-physics/mujoco-usd-converter/#readme
  homepage: https://github.com/newton-physics/mujoco-usd-converter
  license: Apache-2.0
  license_file:
    - LICENSE.md
  repository: https://github.com/newton-physics/mujoco-usd-converter
  summary: A MuJoCo to OpenUSD Data Converter

extra:
  recipe-maintainers:
    - diegoferigo
